steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated=${_ALLOW_UNAUTHENTICATED}'
      - '--service-account'
      - '${_RUNTIME_SA}'
      - '--port=80'
      - '--set-env-vars=LIMS_API_UPSTREAM=${_LIMS_API_UPSTREAM}'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'asia-south1'
  _AR_REPO: 'hale-lims'
  _SERVICE_NAME: 'hale-lims-web'
  _DOCKERFILE: 'Dockerfile'
  _ALLOW_UNAUTHENTICATED: 'true'
  _RUNTIME_SA: 'lims-web-sa@PROJECT_ID.iam.gserviceaccount.com'
  _LIMS_API_UPSTREAM: 'https://hale-lims-CHANGE_ME.a.run.app'
